name: 'Register Discord Bot Slash Commands'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment (dev or prod)
        required: true
        type: choice
        options:
          - dev
          - prod
      command_name:
        description: Name of command to register/update
        required: true
        type: string

  workflow_call:
    inputs:
      environment:
        description: Deployment environment (dev or prod)
        required: true
        type: string
      command_name:
        description: Name of command to register/update
        required: true
        type: string
    secrets:
      DISCORD_BOT_TOKEN_DEV:
        required: true
      DISCORD_BOT_TOKEN_PROD:
        required: true

jobs:
  register-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        shell: bash
        run: |
          ENV_NAME="${{ inputs.environment }}"

          # Set variables directly into the $GITHUB_ENV for all subsequent steps
          if [ "$ENV_NAME" == "prod" ]; then
            echo "DISCORD_APP_ID=${{ vars.DISCORD_APP_ID_PROD }}" >> $GITHUB_ENV
            echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN_PROD }}" >> $GITHUB_ENV
          else
            echo "DISCORD_APP_ID=${{ vars.DISCORD_APP_ID_DEV }}" >> $GITHUB_ENV
            echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN_DEV }}" >> $GITHUB_ENV
          fi

          echo "COMMAND_NAME=${{ inputs.command_name }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name:
          Register commands
          # env vars read thru $GITHUB_ENV
        run: |
          python scripts/register_commands.py
